### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by ryanwinchester**

### CODE REVIEW

**Comment by jesseshieh** [comment]
Thank you! This is awesome. I'm going to take a closer look as soon as I can. I'm not that familiar with why some of the changes were made so I'll need to do some research.

**Comment by ryanwinchester** [comment]
I mostly added [pin operator](https://elixir-lang.org/getting-started/pattern-matching.html#the-pin-operator).

If you assigned a variable and then immediately used it in a match, I just assumed you wanted it to be matched on, otherwise you assigned it for no reason (and compiler warned of unused variables).

**Comment by jesseshieh** [comment]
Looks great! Thanks!

**Comment by TheFirstAvenger** [comment]
@jesseshieh Could we get a new version pushed to hex with this fix? Thanks!

**Comment by jesseshieh** [comment]
Oh sure. Sorry about that. I'll do that as soon as I can.

**Comment by jesseshieh** [comment]
Okay, published as v0.1.1
https://hex.pm/packages/master_proxy

**Pull request merged**
