### PR TITLE
Update to support Phoenix 1.7

### LINKED ISSUE #28: Update `main_proxy` to support Phoenix 1.7
Having upgraded an umbrella app to Phoenix 1.7, `main_proxy` errors out because `Phoenix.Endpoint.Cowboy2Handler` has been removed. 

```
[error] Ranch protocol #PID<0.747.0> of listener HTTP (connection #PID<0.746.0>, stream id 1) terminated
an exception was raised:
    ** (UndefinedFunctionError) function Phoenix.Endpoint.Cowboy2Handler.init/2 is undefined (module Phoenix.Endpoint.Cowboy2Handler is not available)
        Phoenix.Endpoint.Cowboy2Handler.init(%{...}, {MyApp.Endpoint, []})
        (cowboy 2.9.0) /app_umbrella/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /app_umbrella/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) //app_umbrella/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

### PR DESCRIPTION
**Pull request by axelson**
Update to support Phoenix 1.7-rc.2

With the websock changes that have come in Phoenix 1.7 the custom Cowboy handler is no longer needed (as discussed at https://elixirforum.com/t/mainproxy-run-multiple-phoenix-apps-on-one-port/51067/5?u=mtrudel) and now we just need a pretty simple plug.

I took the occasion to slightly refactor the `MainProxy.Proxy` module and moved it's common code over to the `MainProxy` module.

Try this out in your own project by using this as the `main_proxy` dep in your mix.exs:
`{:main_proxy, github: "axelson/main_proxy", branch: "ugprade-to-1.7-redux"}`
(yes there is a typo in my branch name)

Fixes #28

### CODE REVIEW

**Comment by gf3** [comment]
so far this seems to be working well 🎉 thank you

although i'm having some difficulty correctly routing the live reload socket between backends. i'm not sure if that's something that requires special attention in main proxy

**Comment by gf3** [comment]
i did a little more research and found that the path is hardcoded here:

https://github.com/phoenixframework/phoenix_live_reload/blob/43b923b2d909b8af55e4b905fecab7aabef43879/lib/phoenix_live_reload/live_reloader.ex#L119

after asking around on the elixir slack, an example was linked [using `Plug.forward/4`](https://hexdocs.pm/plug/1.14.0/Plug.html#forward/4):

```elixir
defmodule Router do
  def init(opts), do: opts

  def call(conn, opts) do
    case conn do
      # Match subdomain
      %{host: "admin." <> _} ->
        AdminRouter.call(conn, opts)

      # Match path on localhost
      %{host: "localhost", path_info: ["admin" | rest]} ->
        Plug.forward(conn, rest, AdminRouter, opts)

      _ ->
        MainRouter.call(conn, opts)
    end
  end
end
```

in the second match you can see that the `/admin` portion of the path is popped off and the request is forwarded along without it

is it possible to add similar functionality to main proxy?

**Comment by gmile** [comment]
After adding this to mix:

```
{:main_proxy, github: "axelson/main_proxy", branch: "ugprade-to-1.7-redux"},
```

`mix deps.get` stops with an error:

```
mix deps.get
* Updating main_proxy (https://github.com/axelson/main_proxy.git - origin/ugprade-to-1.7-redux)
Resolving Hex dependencies...
Resolution completed in 0.043s
Because your app depends on phoenix empty which doesn't match any versions, version solving failed
```

What helped is updating phoenix dependency in our app from:

```
{:phoenix, "~> 1.7"},
```

to:

```
{:phoenix, "~> 1.7", override: true},
```

Could be because phoenix version is specified explicitly as `1.7.0-rc.2` on this branch? Haven't looked deeper into this, for now just leaving a comment before I forget)

**Comment by gmile** [comment]
ℹ️ we've been running this branch in production for a few days now, no issues so far

**Comment by axelson** [comment]
Thank you for the report! Yeah `override: true` is necessary for now with
the branch. I'm planning to cut a release over the weekend.

**Comment by axelson** [comment]
> i did a little more research and found that the path is hardcoded here:
> 
> https://github.com/phoenixframework/phoenix_live_reload/blob/43b923b2d909b8af55e4b905fecab7aabef43879/lib/phoenix_live_reload/live_reloader.ex#L119
> 
> after asking around on the elixir slack, an example was linked [using `Plug.forward/4`](https://hexdocs.pm/plug/1.14.0/Plug.html#forward/4):
> 
> ```elixir
> defmodule Router do
>   def init(opts), do: opts
> 
>   def call(conn, opts) do
>     case conn do
>       # Match subdomain
>       %{host: "admin." <> _} ->
>         AdminRouter.call(conn, opts)
> 
>       # Match path on localhost
>       %{host: "localhost", path_info: ["admin" | rest]} ->
>         Plug.forward(conn, rest, AdminRouter, opts)
> 
>       _ ->
>         MainRouter.call(conn, opts)
>     end
>   end
> end
> ```
> 
> in the second match you can see that the `/admin` portion of the path is popped off and the request is forwarded along without it
> 
> is it possible to add similar functionality to main proxy?

@gf3 Can you open up a separate issue for that? Ideally with a reproducible example. On first glance it seems like something that should be handleable on the main-proxy side, but some more investigation is needed.

**Pull request merged**
